audit_header: false
title: Tulsa Real Estate Video Blog with Jennie Wolek
description: >-
  Our mission at -- CLIENT BRAND -- is to be your best resource for -- MARKET --
  real estate advice. Whether you are a buyer, seller, or investor, our team of
  professionals can answer any questions you might have about real estate. If
  you are looking to buy or sell a home, you can get all the information and the
  latest updates, tips, and tricks from The -- CLIENT BRAND --, your
  professional -- MARKET -- Real Estate Agents.
show_custom_links: true
custom_links:
  - title: Free Newsletter
    url: /subscribe/
client:
  name: The Wolek Group
  title:
  license_number:
  about_markdown: >
    Our mission is to deliver on our Promise and provide the highest quality
    client experience with a sense of warmth and friendliness. We have a
    learning-based culture that is dedicated to giving back to our clients and
    the community.  We commit to support our local business partners and empower
    our youth through education and personal growth.


    Our Promise:
      <ul class="about-list">
      <li>• To work as a team to ensure a smooth and seamless transaction from start to finish.</li>
      <li>• To exceed expectations by being solution-based.</li>
      <li>• To make every effort to be proactive and limit surprises.</li>
      <li>• To provide exceptional service by being honest, loyal, understanding and attentive.</li>
      <li>• To guarantee each client receives such an outstanding experience that they always think of and recommend The Wolek Group to friends and family for any real estate needs.</li>
      </ul>
  market: Tulsa
  brand: Keller Williams Realty Advantage
  brokerage:
  address: '2651 E. 21st Street, Ste 100 Tulsa, OK, 74114'
  phone: 918-550-9243
  phone_type:
  phone2:
  phone2_type:
  email: info@TheWolekGroup.com
  url: 'https://www.thewolekgroup.com'
CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: 'http://www.tulsahomevalue.com/'
  second_CTA_text: Home Search
  second_CTA_URL: >-
    https://www.thewolekgroup.com/search#?q_limit=36&q_prioritize=agents.0.id=173675|office.id=127576&mlsId=291&status=1|3&q_sort=createdAt-&q_offset=0
sidebar_CTA:
  - CTA_image_path: /img/cta-images/004.jpg
    CTA_title: What’s Your -- MARKET -- Home Worth?
    CTA_text: >-
      Are you thinking of selling your home or interested in learning about home
      prices in your neighborhood? We can help you.
    CTA_link_text: Free Home Value Report
    CTA_url: 'http://www.tulsahomevalue.com/'
second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/005.jpg
    CTA_title2: Looking for a -- MARKET -- Home?
    CTA_text2: Search the entire MLS for your -- MARKET -- home.
    CTA_link_text2: Search the MLS
    CTA_url2: >-
      https://www.thewolekgroup.com/search#?q_limit=36&q_prioritize=agents.0.id=173675|office.id=127576&mlsId=291&address.neighborhood=undefined&status=1|3&q_sort=createdAt-&q_offset=0
lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: 'http://fillmurray.com/200/200'
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: 'http://eyegoop.com'
socials:
  review_sm_icons: false
  facebook_url: 'https://www.facebook.com/tulsaokrealestate'
  linkedin_url: 'https://www.linkedin.com/in/jenniewolek/'
  youtube_url: 'https://www.youtube.com/channel/UC_9WYLbPpZ-8eZz3u8NMnYg'
  twitter_url:
  instagram_url: 'https://www.instagram.com/thewolekgrouptulsa/'
  pinterest_url:
  zillow_url: 'http://www.zillow.com/profile/jwolek/'
  trulia_url: 
  yelp_url: 
  facebook_reviews_url: https://www.facebook.com/tulsaokrealestate/reviews?ref=page_internal
  google_reviews_url: >-
    https://www.google.com/search?q=jennie+wolek&oq=jennie+wolek&aqs=chrome..69i57j69i60j69i61j69i60.3684j0j1&sourceid=chrome&ie=UTF-8#lrd=0x87b6ecc33325418f:0x8afdb81dd6349e30,1
  podcast_url: >-
    https://itunes.apple.com/us/podcast/tulsa-ok-real-estate-podcast-jennie-wolek-wolek-group/id1199631440?mt=2
podcast:
  title: Tulsa Looks Good on You
  categories:
    - Education
  image: /img/podcast.png
  subtitle: >-
    Learn all the tips, tricks and more for buyers and sellers in the -- MARKET
    -- Area Real Estate Market
  description: >-
    If you are looking to buy or sell a home, get all the information and the
    latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional
    -- MARKET -- Real Estate Agents.
  keywords: >-
    Real Estate for sale, Real Estate agents, top real estate agents, local real
    estate agents, find a real estate agent, houses for sale in -- MARKET --,
    home selling tips, home for sale, home buying, home buying process, property
    finder, property search, property, real estate market, estate agent,
    realestate, real estate listings, buying a house, homes for sale, mls, home
    buyer
  author: '-- CLIENT NAME --'
images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo1.png
  logo_width_number: 60
  hero_text:
  hero_background_hex: '#15355b'
  hero_image_path: /img/background1.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#11365c'
  theme_color: '#9bb6bd'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'
navbar_colors:
  border_bottom:
header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: '#15355b'
buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: 'rgba(0, 0, 0, 0)'
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'