audit_header: false
title: "The Stern Team: Home Page"
description: 'Salt Lake City Utah best Realtors are on The Stern Team, led by Joshua Stern. Follow us for latest market info and be prepared to buy or sell real estate.'
show_custom_links: true
custom_links:
  - title: About
    url: http://www.viewsaltlakecityareahomes.com/about/
  - title: Testimonials
    url: https://soundcloud.com/joshua-stern-5
client:
  name: Joshua Stern
  license_number:
  about_markdown: |
    The Stern Team is a full service real estate team that has helped sell and purchase thousands of homes since 2002 - currently about a property a day! Commitment to servicing their clients and the “client experience” has lead to over 83% of their business coming by referral.

    The Stern Team motto is “clients don’t care how much we know, until they know how much we care”. Their philosophy is that when you take care of others needs, your needs are automatically taken care of. The Stern Team is one of the top real estate groups in North America and the #1 resale team in Utah.

    If you’re looking to buy, sell or invest in a home to live in Salt Lake, Joshua Stern and his team are here to ensure you have an excellent real estate experience.
  market: Salt Lake City
  brand: The Stern Team
  brokerage: KW Salt Lake City Keller Williams Real Estate
  address: "2121 S McClelland, Ste. #201<br>Salt Lake City, UT 84106"
  phone: 385-999-7273
  phone_type:
  phone2:
  phone2_type:
  email: successteam@sternteam.com
  url: http://sternteam.org
  first_CTA_text: Did You Hear Us on the Radio?
  first_CTA_URL: http://sternsellshomes.com/
  # second_CTA_text: Home Search
  # second_CTA_URL: https://www.sternteam.com/
  phone_CTA: false

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: https://www.sternteam.com/homevalue/ssl-homevalue
  second_CTA_text: Home Search
  second_CTA_URL: https://www.sternteam.com/

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "What’s My Home Worth?"
    CTA_link_text: "Free Home Value Report"
    CTA_url: https://www.sternteam.com/homevalue/ssl-homevalue

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: "Thinking of Buying a Home?"
    CTA_link_text2: "Search All Homes"
    CTA_url2: https://www.sternteam.com/

welcome_headline: Get Educated About Real Estate
welcome_text_markdown: |
  Our mission at The Stern Team is to be your best resource for real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. Subscribe to this blog to get the latest news on local market trends and receive expert tips for buying or selling a home.
socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/thesternteam/
  linkedin_url: https://www.linkedin.com/company/thesternteam 
  youtube_url: https://www.youtube.com/user/JoshuaSternTeam/featured?view_as=public
  twitter_url: https://twitter.com/thesternteam 
  instagram_url: https://www.instagram.com/thesternteam/
  pinterest_url:
  zillow_url:  http://www.zillow.com/profile/sternteam/
  trulia_url:
  yelp_url: http://www.yelp.com/biz/joshua-stern-salt-lake-city
  podcast_url: https://itunes.apple.com/us/podcast/salt-lake-county-real-estate/id1183406593?mt=2
podcast:
  title: Salt Lake City Real Estate Podcast with Joshua Stern
  categories: News &amp; Politics
  image: /img/Stern_podcast.png
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Salt Lake City Real Estate Market'
  description: 	If you are looking to buy or sell a Salt Lake City home, get all the information and the latest updates, tips, and tricks from The Stern Team - your professional Salt Lake City Real Estate Agents.
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Salt Lake City, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: Joshua Stern

agent:
  name: Jeremy Martin
  email: jeremy@sternteam.com
  phone: 801-598-9838
  name2: Jennifer Okobia
  email2: jennifer@sternteam.com
  phone2: 801-834-2900
  name3: Jacquie Reagh
  email3: jacquie@sternteam.com
  phone3: 619-540-5157

images:
  client_headshot_path1: '/img/lee.jpg'
  client_headshot_path2: '/img/ken.jpg'
  client_headshot_path3: '/img/emily.jpg'
  hero_logo_path: '/img/logo.png'
  hero_background_hex: '#ab0000'
  hero_image_path: '/img/background.jpg'
  hero_image_path2: '/img/background2.jpg'
brand_color: '#ab0000'
theme_color: '#ab0000'
theme_text_color: '#353535'
main_body_color: '#ffffff'
main_body_text_color: '#353535'
