audit_header: false
title: Your Journey with Jennie | Jennie Wolek
description: >-
  Jennie Wolek, a top Real Estate Agent in Tulsa, shares her own internal real
  estate agent training for free. Her Real Estate Training, Tips and Advice will
  help you sell more homes in less time.
show_custom_links: true
custom_links:
  - title: Join Our Team
    url: /join-our-team/
  - title: About
    url: /about/
  - title: Events
    url: >-
      https://www.eventbrite.com/o/jennie-wolek-the-wolek-group-keller-williams-realty-advantage-17487334418
  - title: Free Newsletter
    url: /subscribe/
  - title: Join Maintain Your Momentum
    url: /momentum/
  - title: Join My Facebook Group!
    url: https://www.facebook.com/groups/yourjourneywithJennie/
  - title: testimonials
    url: /testimonials/
  - title: Buy Now!
    url: /buy-now/
emma:
  lightbox:
  form:
client:
  name: Jennie Wolek
  title:
  license_number:
  about_markdown: >-
    Jennie Wolek and her team, The Wolek Group helped 191 families in 2021 buy
    and sell real estate in Tulsa, OK. Most of their business comes from their
    database or a personal referral. Jennie shares the systems and tools used by
    The Wolek Group and also interviews top agents who give insight to their
    success secrets as well.
  market: Tulsa
  brand: The Wolek Group
  brokerage: Keller Williams Realty
  address: '2651 E 21st St #100<br>Tulsa, OK 74114'
  phone: (918) 550-9243
  phone_type:
  phone2:
  phone2_type:
  email: Jennie@TheWolekGroup.com
  url: https://www.thewolekgroup.com
CTAs:
  first_CTA_text: Apply Here
  first_CTA_URL: /apply/
  second_CTA_text: Send Us a Referral
  second_CTA_URL: http://www.thewolekgroup.com/contact/
sidebar_CTA:
  - CTA_image_path: /img/cta-images/006.jpg
    CTA_title: Join Our Tulsa Real Estate Team
    CTA_text: >-
      You will learn how to focus on what is most important - running a great
      business while helping your clients achieve their goals and dreams.
    CTA_link_text: Apply Here
    CTA_url: /apply/
second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/005.jpg
    CTA_title2: Send Us a Referral
    CTA_text2:
    CTA_link_text2: Get Started
    CTA_url2: http://www.thewolekgroup.com/contact/
lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com
socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/groups/yourjourneywithJennie/
  linkedin_url: https://www.linkedin.com/in/jenniewolek/
  youtube_url: https://www.youtube.com/channel/UC_9WYLbPpZ-8eZz3u8NMnYg
  twitter_url:
  instagram_url:
  pinterest_url:
  podcast_url: >-
    https://itunes.apple.com/us/podcast/tulsa-ok-real-estate-careers/id1199634583?mt=2
podcast:
  title: Your Journey with Jennie Podcast
  categories:
    - Education
  image: /img/podcast.jpg
  subtitle: >-
    Learn all the tips, tricks and more for buyers and sellers in the Tulsa Area
    Real Estate Market
  description: >-
    While on Your Journey with Jennie, you will learn all the systems, tools and
    tips which have allowed her real estate team help over 100 families a year,
    while having lots of fun and spending quality time with family and friends!
  keywords: >-
    Real Estate agents, top real estate agents, local real estate agents, Real
    Estate Training, Real Estate Coaching, Real Estate Agent Tips, Free Real
    Estate Training, home selling tips, home buying, home buying process, estate
    agent, realestate, real estate listings, The Wolek Group, Tulsa Real Estate,
    Tulsa Real Estate Agents, Tulsa Real Estate Market
  author: Jennie Wolek
images:
  client_headshot_path: /uploads/untitled-design.png
  hero_logo_path: /uploads/yjwj-email-dividers.png
  logo_width_number: 50
  hero_text:
  hero_background_hex: '#999999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#9bb6bc'
  accent_color: '#4f1026'
  theme_color: '#14375c'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'
navbar_colors:
  border_bottom:
header_shadow:
  h_shadow: 2px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: '#ffffff'
buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: rgba(0, 0, 0, 0)
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: rgba(0, 0, 0, 0)
  secondary_button_text_color: '#ffffff'
