audit_header: false
title: Colemere Realty and Associates
description: >-
  If you are looking to buy or sell a home, get all the information and the
  latest updates, tips, and tricks from Colemere Realty and Associates - your
  professional Wasatch Front Real Estate Agents.
show_custom_links:
custom_links:
  - title:
    url:
client:
  clients:
    - name: Bryan Colemere
      client_headshot_path: /img/headshot1.jpg
      license:
      phone: (801) 699-4266
      email: bryan@colemererealty.com
    - name: Scott Colemere
      client_headshot_path: /img/headshot2.jpg
      license:
      phone: (801) 403-8565
      email: scott@colemererealty.com
  about_markdown: >-
    As a third generation, **family-owned** and operated real estate company,
    **Colemere Realty Associates** has a long history of working for the success
    of our clients. Each member of our team is focused on providing **the
    expertise of 3 generations in the business**. We know that a real estate
    transaction can be very challenging which is why achieving your satisfaction
    is our top priority. As your **REALTORS&reg;**, we are **committed to your
    success** in the purchase and sale of your home, and we promise you the full
    support, experience, and expertise of our team.
  market: Wasatch Front
  brand: 'Colemere Realty Associates, LLC'
  brokerage:
  address: '9661 S 700 E<br>Sandy, UT 84070'
  office_phone: (801) 272-8192
  office_email: info@colemererealty.com
  url: 'http://colemererealty.com/'
  first_CTA_text: Home Evaluation
  first_CTA_URL: 'https://www.colemererealty.com/sell/'
  second_CTA_text: Home Search
  second_CTA_URL: 'https://www.colemererealty.com/'
  about_header: About the CRA Team
emma_form: >-
  <script
  id="e2ma-embed">window.e2ma=window.e2ma||{};e2ma.accountId='1808174';</script><script
  src="//dk98ddgl0znzm.cloudfront.net/e2ma.js" async="async"></script>
welcome_headline: Get Educated About Your Real Estate
welcome_text_markdown: >-
  Our mission at Colemere Realty and Associates is to be your best resource for
  real estate advice. Our team of professionals can answer any questions you
  might have about real estate. Subscribe to this blog to get the latest news on
  real estate and receive expert tips for preparing yourself for your buying or
  selling a home.
socials:
  review_sm_icons: false
  facebook_url: 'https://www.facebook.com/Colemere-Realty-Associates-207059249365713/'
  linkedin_url: 'https://www.linkedin.com/in/bryan-colemere-21b4a03/'
  gplus_url:
  youtube_url: 'https://www.youtube.com/channel/UC3MPsAkkbFjc6lNxgDshMLQ'
  twitter_url: 'https://twitter.com/bryancolemere'
  instagram_url:
  pinterest_url:
  zillow_url: 'http://www.zillow.com/profile/bcolemere/'
  trulia_url:
  yelp_url: 'https://www.yelp.com/biz/bryan-colemere-colemere-realty-riverton'
  podcast_url: >-
    https://itunes.apple.com/us/podcast/colemere-realty-associates/id1177583830?mt=2
podcast:
  title: Colemere Realty and Associates Real Estate Podcast
  categories:
  image: /img/colemere_podcast.jpg
  subtitle: >-
    Learn all the tips, tricks and more for buyers and sellers in the Portland
    Area Real Estate Market
  description: >-
    If you are looking to buy or sell a home, get all the information and the
    latest updates, tips, and tricks from Colemere Realty and Associates - your
    professional Wasatch Front Real Estate Agents.
  keywords: >-
    Real Estate for sale, Real Estate agents, top real estate agents, local real
    estate agents, find a real estate agent, houses for sale in Wasatch Front,
    home selling tips, home for sale, home buying, home buying process, property
    finder, property search, property, real estate market, estate agent,
    realestate, real estate listings, buying a house, homes for sale, mls, home
    buyer
  author: Bryan Colemere
images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  hero_text:
  hero_background_hex: '#0b2972'
  hero_image_path: /img/background.jpg
brand_color: '#02084b'
theme_color: '#0b2972'
theme_text_color: '#353535'
main_body_color: '#ffffff'
main_body_text_color: '#353535'