title: 'Wasatch Front Real Estate Video Blog with Bryan and Scott Colemere'
description: >-
  Our mission at -- CLIENT BRAND -- is to be your best resource for -- MARKET --
  real estate advice. Whether you are a buyer, seller, or investor, our team of
  professionals can answer any questions you might have about real estate. If
  you are looking to buy or sell a home, you can get all the information and the
  latest updates, tips, and tricks from The -- CLIENT BRAND --, your
  professional -- MARKET -- Real Estate Agents.
show_custom_links: true
custom_links:
  - title: Guaranteed Offer
    url: /guaranteed-offer/
forms:
  sitekey: 6LdYnCwaAAAAAAvUt2CT8CsTa477liWkwqtzo5dO
client:
  clients:
    - name: Bryan Colemere
      client_headshot_path: /img/headshot1.jpg
      license:
      phone: (801) 699-4266
      email: bryan@colemererealty.com
    - name: Scott Colemere
      client_headshot_path: /img/headshot2.jpg
      license:
      phone: (801) 403-8565
      email: scott@colemererealty.com
  about_markdown: >-
    As a third generation, **family-owned** and operated real estate company,
    **Colemere Realty Associates** has a long history of working for the success
    of our clients. Each member of our team is focused on providing **the
    expertise of 3 generations in the business**. We know that a real estate
    transaction can be very challenging which is why achieving your satisfaction
    is our top priority. As your **REALTORS&reg;**, we are **committed to your
    success** in the purchase and sale of your home, and we promise you the full
    support, experience, and expertise of our team.
  market: Wasatch Front
  brand: 'Colemere Realty Associates, LLC'
  brokerage:
  address: '9661 S 700 E<br>Sandy, UT 84070'
  office_phone: (801) 272-8192
  office_email: info@colemererealty.com
  url: 'http://colemererealty.com'
  first_CTA_text: Home Evaluation
  first_CTA_URL: 'https://www.colemererealty.com/sell/'
  second_CTA_text: Home Search
  second_CTA_URL: 'https://www.colemererealty.com/'
  about_header: About the CRA Team
emma_form: >-
  <script
  id="e2ma-embed">window.e2ma=window.e2ma||{};e2ma.accountId='1808174';</script><script
  src="//dk98ddgl0znzm.cloudfront.net/e2ma.js" async="async"></script>
socials:
  review_sm_icons: false
  facebook_url:
  linkedin_url:
  youtube_url:
  twitter_url:
  instagram_url:
  pinterest_url:
  zillow_url: 'http://www.zillow.com/profile/bcolemere/'
  trulia_url:
  yelp_url: 'https://www.yelp.com/biz/bryan-colemere-colemere-realty-riverton'
  podcast_url: >-
    https://itunes.apple.com/us/podcast/colemere-realty-associates/id1177583830?mt=2
CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: /homevalue/
  second_CTA_text: Home Search
  second_CTA_URL: /homesearch/
sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: Whatâ€™s Your -- MARKET -- Home Worth?
    CTA_text: >-
      Are you thinking of selling your home or interested in learning about home
      prices in your neighborhood? We can help you.
    CTA_link_text: Free Home Value Report
    CTA_url: /homevalue/
second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: Looking for a -- MARKET -- Home?
    CTA_text2: Search the entire MLS for your -- MARKET -- home.
    CTA_link_text2: Search the MLS
    CTA_url2: /homesearch/
podcast:
  title: Colemere Realty and Associates Real Estate Podcast
  categories:
  image: /img/colemere_podcast.jpg
  subtitle: >-
    Learn all the tips, tricks and more for buyers and sellers in the Portland
    Area Real Estate Market
  description: >-
    If you are looking to buy or sell a home, get all the information and the
    latest updates, tips, and tricks from Colemere Realty and Associates - your
    professional Wasatch Front Real Estate Agents.
  keywords: >-
    Real Estate for sale, Real Estate agents, top real estate agents, local real
    estate agents, find a real estate agent, houses for sale in Wasatch Front,
    home selling tips, home for sale, home buying, home buying process, property
    finder, property search, property, real estate market, estate agent,
    realestate, real estate listings, buying a house, homes for sale, mls, home
    buyer
  author: Bryan Colemere
images:
  client_headshot_path: /uploads/colmere-team-2021-short.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: '-- MARKET -- Real Estate Video Blog'
  hero_background_hex: '#999999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
  post_cta_image: /img/home-value.jpg
  post_cta_image2: /img/home-search.jpg
brand_color: '#02084b'
theme_color: '#0b2972'
theme_text_color: '#353535'
main_body_color: '#ffffff'
main_body_text_color: '#353535'
site_colors:
  brand_color: '#b40101'
  theme_color: '#999999'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'
header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: 'rgba(0, 0, 0, 0)'
buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: 'rgba(0, 0, 0, 0)'
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'