audit_header: false
title: Dave Friedman Team
description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
show_custom_links: true
custom_links:
  - title: Culture
    url: /culture/
  - title: Career Track
    url: /career/
  - title: Hiring FAQ's
    url: /hiring-process
  - title: Freebies + Events
    url: /freebies
  - title: Workshop
    url: https://docs.google.com/document/d/16nn8rIXHSiXpS7DNlPJJvm50XI5KXHg7Vtx056t_Ueg/edit
  - title: Contact
    url: /contact
  # - title: Apply Now
  #   url: https://dave-friedman-team.breezy.hr/#positions

client:
  name: Dave Friedman
  license_number:
  about_markdown: |
    Voted Best Realtor and top finalist every year since 2013, it is easy to say that Dave Friedman is committed to his work. These prestigious awards, given to one Realtor out of more than 6,000 in the area, has been earned by Dave. He has been named a Top Producing Realtor for 19 plus years and is the #1 team in the Charleston tri-county area by both families served and volume. He’s also been featured on HGTV’s show House Hunters. Dave has closed over 1,500 transactions over his 19+ years in real estate, earning countless raving fan reviews. He works hard to get the deal a buyer is looking for and averages $10,000 more savings for buyers than the average realtor. Dave sells 95% of his listings within 7 days, and for 100% of asking price for sellers. This exceeds the area averages putting $6,800 more in a sellers pocket and selling it 43 days faster than the average Realtor.

    Despite Dave’s busy professional schedule, he loves spending time with his wife Halley and their pup. Halley is an Auburn grad and Dave roots for anything related to Michigan and Detroit as he grew up in southeastern Michigan. Dave and Halley love sports and staying active in life and in the community. Dave wholeheartedly believes in giving back. He has always been and continues to be extremely involved in several non-profits. He has organized many successful events for local charities and personally donating over $24,000 last year and countless hours served.

    As the owner of one of the top real estate teams in Charleston, Dave has proven that he has what it takes to find or sell your home. Dave has spent the past 19+ years analyzing the home buying and selling process for his clients. He has dedicated his time to streamlining the process and improving the results. Dave surrounds himself with the leading experts in the field and is committed to continuing education so that he can always ensure he’s offering the best advice and information for today’s market. Part of Dave’s business philosophy is that it’s better to be great at one thing than to be okay at several things. That’s why Dave has hired a team of experts to work alongside him, from client care coordinators to closing experts, photographers, stagers, to professional writers. Dave’s clients know they are always receiving top-notch professionalism and expertise.

    If you are looking for a realtor who has a proven track record of earning his title as Top Producing realtor for over 19 years, call Dave.


  market: Charleston
  brand: Dave Friedman Team
  brokerage: Keller Williams Charleston
  address: 496 Bramson Court Suite 160A<br>Mount Pleasant SC 29464
  phone: 843-800-2465
  phone_type:
  phone2:
  phone2_type:
  email: Careers@DaveFriedmanTeam.com
  url: http://www.ClickCharlestonSC.com

CTAs:
  first_CTA_text: Apply Now
  first_CTA_URL: https://dave-friedman-team.breezy.hr/#positions
  second_CTA_text:
  second_CTA_URL:

sidebar_CTA:
  - CTA_image_path: /img/cta-images/006.jpg
    CTA_title: Looking to Build Your Real Estate Career?
    CTA_text: Let's talk about how The Dave Friedman Team can take your business to new heights.
    CTA_link_text: Join Our Team
    CTA_url: /join-our-team

lender:
  show_section: true
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.jpg
  logo_path_2:
  name: Matthew Mieras, Branch Manager
  license_number: 'NMLS #245686'
  brand: CMG Financial
  brand_license_number: 'NMLS #1820'
  address: 765 Long Point Road Suite A<br>Mt. Pleasant, SC 29464
  phone: 843-670-5512
  email: MMieras@cmgfi.com
  url: https://www.cmgfi.com/agents/matthew-mieras

welcome_box:
  welcome_headline: How to Sell More Homes
  welcome_text_markdown: >
    Whether you are just starting out, or you are licensed Broker, our team of professionals can answer any questions you might have about real estate.
    Subscribe to this blog to get the latest news on local market trends and receive expert tips for buying or selling a home.

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/chsagentmastermind/
  linkedin_url: https://www.linkedin.com/company/dave-friedman-team/
  youtube_url: https://www.youtube.com/channel/UCYg5beOA0R1xWVZqukzSNBA
  twitter_url: https://twitter.com/RealEstateRants
  instagram_url:
  pinterest_url:
  zillow_url: http://www.zillow.com/profile/Dave-Friedman/
  trulia_url: http://www.trulia.com/profile/dave-friedman-agent-charleston-sc-9567361/overview
  yelp_url: http://www.yelp.com/biz/dave-friedman-real-estate-mount-pleasant
  podcast_url:

podcast:
  title:
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 30
  hero_text: <br>
  hero_image_path: /img/background.jpg
  hero_background_hex: '#FFF'
  post_cover: /img/cover.jpg
  broker_logo: /img/kw.png

site_colors:
  brand_color: '#B40101'
  theme_color: '#4E4A46'
  theme_text_color: '#353535'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: rgba(61, 44, 50, .8)

buttons:
  button_radius_number: 0
  button_padding_width_number: 20
  button_padding_height_number: 15
  button_border_color: '#B40101'
  button_background_color: '#B40101'
  button_text_color: '#fff'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
